baseurl = "/"
languageCode = "en-us"
title = "Playflow"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 1
canonifyurls = true

[params]
  description = "For real"
  cover = "images/cover.jpg"
  author = "Playflow"
  authorlocation = "Hong Kong"
  authorwebsite = ""
  bio= ""
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-108104539-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = ""
  twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = ""
